language: rust

rust:
  - nightly
  - stable

cache: cargo
sudo: false
# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

before_script:
  - pip install 'travis-cargo<0.2' --user
  - cargo install rustfmt
  - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH

script:
  - |
    cargo fmt -- --write-mode=diff &&
    travis-cargo build &&
    travis-cargo test &&
    travis-cargo bench &&
    travis-cargo --only stable doc

after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo coveralls --no-sudo --verify
